language: node_js

node_js:
  - "12"
  - "14"
  - "16"
  - "node"

install:
  - "npm install"
  - "npm install @hapi/hapi@$HAPI_VERSION"

env:
  - HAPI_VERSION="17"
  - HAPI_VERSION="18"
  - HAPI_VERSION="19"
  - HAPI_VERSION="20"
